apiVersion: v1
kind: Service
metadata:

  name: ingress-svc

  labels:
    app: ingress-svc

spec:

  type: $SERVICE_TYPE
  loadBalancerIP: $LOADBALANCER_IP
  ports:

  - port:       80
    targetPort: 80
    name:       http

  - port:       443
    targetPort: 443
    name:       https

  - port:       1194
    targetPort: 1194
    name:       openvpn

  selector:
    k8s-app: ingress-controller
